name: debug.yml

on:
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  echo_dir:
    name: Output Directory
    runs-on: ubuntu-latest
    steps:
      - name: debug
        run: |
          echo "github.path ${{github.path}}"
          echo "GITHUB_WORKSPACE ${GITHUB_WORKSPACE}"
          echo "GITHUB_PATH ${GITHUB_PATH}"
          echo "RUNNER_TEMP ${RUNNER_TEMP}"
